backend:
  name: github
  repo: selektiert/website
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: https://api.netlify.com/auth

media_folder: "SRC"
public_folder: "/SRC"

collections:
  - name: "event"
    label: "Event"
    files:
      - file: "event.json"
        label: "Upcoming Event"
        name: "event"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Location", name: "location", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
